### ISSUE TITLE
Avoid copying GitHub CLI release notes to this repo

### ISSUE THREAD

**Issue by mislav** [jenkins-infra/docker-builder#27]
When full GitHub CLI release notes are copied to the issue/PR body in this repo (e.g. https://github.com/jenkins-infra/docker-builder/pull/26), everyone who got @-mentioned in the GitHub CLI release notes has now also been pinged about this repository, and every GitHub CLI PR referenced in the release now has a cross-reference to the PR in your repository as well. This is noisy behavior and it should absolutely be avoided.

The quickest workaround you could make right now is to link to GitHub CLI release notes instead of quoting them verbatim.

**Comment by dduportal** [comment]
Hi @mislav , sorry for bothering you.

This is a behavior from the tools we are using, https://github.com/updatecli/updatecli: we need to cut a patch release on this tool and apply it.

The bug is that the markdown generated from the release is not correctly escaped (it should use quadruple backticks instead of triple).

We'll change it as soon as possible.

**Comment by mislav** [comment]
Thanks for the fast reply! 🙇

**Comment by dduportal** [comment]
> Thanks for the fast reply! 🙇

You are welcome. Courtesy of @lemeurherve who is our 🦅 👁️ ;)

We have patched updatecli and the patch is deployed, so you should not be bothered again.

Sorry for the disturbance in the force 😱
